name: cool
version: 0.1.0.0
github: "KorigamiK/cool-reanimate"
license: BSD3
author: "Kushagra Lakhwani (KorigamiK)"
maintainer: "korigamik@gmail.com"
copyright: "2023 Kushagra Lakhwani (KorigamiK)"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
synopsis:              "A test on the Reanimate package"
category:              Math, Animation

description: Please see the README on GitHub at <https://github.com/KorigamiK/cool-reanimate#readme>

dependencies:
  - base >= 4.7 && < 5
  - reanimate >= 1.1.4.0
  - reanimate-svg >= 0.13.0.1
  - JuicyPixels
  - lens
  - text
  - random
  - random-shuffle

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Lib

executables:
  cool-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      # - -fsimpl-tick-factor=N
      # - -funfolding-case-threshold=N
      # - -funfolding-case-scaling=N
    dependencies:
      - cool
    when:        
      - condition: false        
        other-modules: Paths_cool

tests:
  cool-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - cool
