resolver: lts-18.28

# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
#   subdirs:
#   - auto-update
#   - wai
packages:
  - .

# extra-deps:
# - acme-missiles-0.3
# - git: https://github.com/commercialhaskell/stack.git
#   commit: e7b331f14bcffb8367cd58fbfc8b40ec7642100a
extra-deps:
  - reanimate-1.1.5.0
  - reanimate-svg-0.13.0.1

# system-ghc: true
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
allow-newer: true
